# openapi2-functions.yaml
swagger: '2.0'
info:
  title: billiards
  description: API to fetch plot from Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/string
paths:
  /polygon:
      get:
        operationId: billiards
        summary: Returns a plot of polygon billiard
        x-google-backend:
          address: https://us-central1-personal-web-409300.cloudfunctions.net/billiards
          path_translation: APPEND_PATH_TO_ADDRESS
        security:
          - api_key: []
        parameters:
          - name: n
            in: query
            description: number of colissions
            required: false
            type: integer
          - name: x
            in: query
            description: x position
            required: false
            type: number
          - name: y
            in: query
            description: y position
            required: false
            type: number
          - name: curve
            in: query
            description: curve of polygon
            required: false
            type: number
          - name: eta
            in: query
            description: mass distribution
            required: false
            type: number
          - name: sides
            in: query
            description: number of sides of polygon
            required: false
            type: integer
          - name: alpha
            in: query
            description: initial angle
            required: false
            type: number
          - name: spin
            in: query
            description: initial spin velocity
            required: false
            type: number
        responses:
          200:
            description: OK
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"